# -*- coding: utf-8 -*-
"""
character/semantic_memory.py —— Character Semantic Memory + Accessory Adaptation Planner（规格 §5 / §19）

- generate_character_memory : 解析角色图片 -> 融合 §5.1 与 §6.2 字段 ->
                              写 output/semantic/{folder}_character_memory.json（UTF-8, indent=2）
- load_character_memory     : 已存在直接读取；不存在则生成；全部失败回退 get_default_memory
                              （只读 dataset/，写 output/semantic/，不修改原始数据集）
- AccessoryAdaptationPlanner: 输入主体语义 + 配饰语义 -> 迁移规划 dict（§19 结构）。
                              主路径 VLM（ACCESSORY_PROMPT），失败/无 client -> 规则表兜底
                              （覆盖规格 §8.4 / §8.5 全部示例）
- build_transfer_prompt     : 按 subject_type 三模板组装迁移 prompt（§16.1 人物 / §16.2 动物 /
                              §16.3 物品 / unknown 保守模板），含 §17 画风保持 token
"""

import json
import os
import sys

# 保证从任意位置直接运行本文件时都能 import 到项目根目录的模块
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

import config  # noqa: E402
from dataset import load_captions  # noqa: E402
from character import character_parser  # noqa: E402
from vlm.vlm_utils import ACCESSORY_PROMPT, get_default_memory  # noqa: E402
from character.transfer_constraints import composition_constraints, fit_prompt, region_visible
from character.object_policy import known_text, object_plan, validate_object_plan


# =========================
# Character Semantic Memory：生成 / 保存 / 读取（规格 §5）
# =========================

def _merge_into_memory(folder: str, char_dict: dict, source: str) -> dict:
    """把 §6.2 角色解析结果融合为 §5.1 语义记忆结构。

    - color_palette 列表前 3 项 -> main / secondary / accent
    - signature_accessories -> accessories（语义角色 / 常规用途映射）+ 原样保留
    - 所有字段都有默认值，VLM 输出缺字段不崩溃
    """
    palette = [p for p in (char_dict.get("color_palette") or [])
               if isinstance(p, str) and p.strip()]
    hair = char_dict.get("hair") or {}
    face = char_dict.get("face") or {}
    clothing = char_dict.get("clothing") or {}

    accessories = []
    for a in (char_dict.get("signature_accessories") or []):
        if not isinstance(a, dict):
            continue
        importance = str(a.get("semantic_importance", "")).lower()
        accessories.append({
            "name": a.get("name", "unknown"),
            "shape": a.get("shape", "unknown"),
            "color": a.get("color", "unknown"),
            "semantic_role": ("character identity symbol" if importance == "high"
                              else "decorative element"),
            "normal_usage": a.get("location", "unknown"),
            "description": a.get("description", ""),
            "source_images": a.get("source_images", []),
        })

    return {
        "folder": str(folder),
        "identity": char_dict.get("character_identity", "unknown"),
        "appearance": {
            "hair": hair.get("color", "unknown"),
            "eyes": face.get("eye_color", "unknown"),
        },
        "color_palette": {
            "main": palette[0] if len(palette) > 0 else "unknown",
            "secondary": palette[1] if len(palette) > 1 else "unknown",
            "accent": palette[2] if len(palette) > 2 else "unknown",
        },
        "clothing": {"style": clothing.get("description", "unknown")},
        "accessories": accessories,
        "signature_accessories": char_dict.get("signature_accessories", []),
        "visual_style": char_dict.get("visual_style", "unknown"),
        "source": source,
        "note": "generated by character semantic memory pipeline",
    }


def generate_character_memory(folder: str, client=None) -> dict:
    """生成并保存角色语义记忆（规格 §5.1 / §5.2）。

    - client 可用 -> VLM 路径（character_parser.parse_character_with_vlm）
    - client 为 None / 不可用 -> offline 兜底（parse_character_offline）
    - 写入 output/semantic/{folder}_character_memory.json（UTF-8、indent=2）
    - 角色文件夹不存在时抛异常（fail fast，指明路径）
    """
    folder_dir = os.path.join(config.DATASET_DIR, str(folder))
    if not os.path.isdir(folder_dir):
        raise FileNotFoundError(f"[semantic_memory] 角色文件夹不存在: {folder_dir}")
    captions = load_captions(os.path.join(folder_dir, "captions.txt"))

    if client is not None and getattr(client, "available", False):
        char_dict = character_parser.parse_character_with_vlm(client, folder_dir, captions)
        source = "vlm"
    else:
        print(f"[semantic_memory] 提示: 无可用 VLM（client={client}），使用 offline 解析")
        char_dict = character_parser.parse_character_offline(captions)
        source = "offline"

    memory = _merge_into_memory(folder, char_dict, source)

    out_path = os.path.join(config.SEMANTIC_DIR, f"{folder}_character_memory.json")
    os.makedirs(config.SEMANTIC_DIR, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(memory, f, ensure_ascii=False, indent=2)
    print(f"[semantic_memory] 已写入角色语义记忆: {out_path}")
    return memory


def load_character_memory(folder: str, client=None) -> dict:
    """读取角色语义记忆（规格 §5.2 / §27 失败回退）。

    - output/semantic/{folder}_character_memory.json 已存在 -> 直接读取（不重复生成）
    - 不存在 -> 调用 generate_character_memory 生成
    - 读取/生成全部失败 -> get_default_memory 兜底
    - 不修改原始数据集（只读 dataset/，仅写 output/semantic/）
    """
    card = config.get_character_card(folder)
    if card:
        # Every consumer sees the same reviewed semantics; keep old cache as evidence.
        return memory_from_card(folder, card)
    path = os.path.join(config.SEMANTIC_DIR, f"{folder}_character_memory.json")
    if os.path.isfile(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                memory = json.load(f)
            if isinstance(memory, dict):
                print(f"[semantic_memory] 直接读取已有记忆（不重复生成）: {path}")
                return memory
            print(f"[semantic_memory] 告警: {path} 内容不是 dict，重新生成")
        except Exception as e:
            print(f"[semantic_memory] 告警: {path} 读取失败（{type(e).__name__}: {e}），重新生成")

    try:
        return generate_character_memory(folder, client)
    except Exception as e:
        print(f"[semantic_memory] 告警: 角色语义记忆生成失败（{type(e).__name__}: {e}），"
              f"回退 get_default_memory")
        return get_default_memory(folder)


def style_policy_for_subject(card, subject):
    """Allow human character rendering without changing animal/object materials."""
    card = card or {}
    if (subject or {}).get("subject_type") == "human":
        return card.get("human_style_policy", card.get("style_policy", "preserve"))
    return card.get("style_policy", "preserve")


def memory_from_card(folder, card):
    palette = list(card.get("palette") or [])
    return {
        "folder": str(folder), "identity": str(folder), "source": "reviewed_card",
        "appearance": {"description": card.get("identity_tags", "")},
        "color_palette": dict(zip(("main", "secondary", "accent"), palette)),
        "accessories": [dict(card.get("accessory") or {})] +
                       list(card.get("secondary_accessories") or []),
        "visual_style": card.get("style", "unknown"),
        "style_policy": card.get("style_policy", "preserve"),
    }


def card_from_memory(memory):
    """Unreviewed characters use the same constrained prompt path, without 37 defaults."""
    appearance = memory.get("appearance") or {}
    identity = []
    for key in ("hair", "eyes"):
        value = appearance.get(key)
        if isinstance(value, str) and value.strip().lower() not in {"", "unknown"}:
            identity.append(value if key in value.lower() else f"{value} {key}")
    accessories = memory.get("accessories") or memory.get("signature_accessories") or []
    acc = next((dict(a) for a in accessories if isinstance(a, dict)), {})
    if not acc.get("description"):
        acc["description"] = ", ".join(str(acc[k]) for k in ("name", "shape", "color")
                                          if acc.get(k) and acc[k] != "unknown")
    return {"core_identity_tags": ", ".join(identity), "identity_tags": ", ".join(identity),
            "accessory": acc, "style_policy": "preserve", "quality_tags": "best quality",
            "palette": [v for v in (memory.get("color_palette") or {}).values()
                        if known_text(v)],
            "source": memory.get("source", "unverified")}


# =========================
# Accessory Adaptation Planner（规格 §19 + §8.4 / §8.5 规则表兜底）
# =========================

# 人物/动物兜底；物品统一走 object_policy 的材质与可见表面规划。
_RULE_FALLBACKS = {
    "human": {
        "adaptation_type": "hair accessory",
        "target_region": "head",
        "material": "glossy plastic",
        "scale": "small",
        "candidates": ["hair accessory", "hair clip", "brooch", "bag charm"],
        "reason": ("Rule-based fallback: human subject has wearable attachment "
                   "points; signature accessory adapted as a small glossy-plastic "
                   "hair accessory on the head."),
    },
    "animal": {
        "adaptation_type": "collar charm",
        "target_region": "neck",
        "material": "soft fabric",
        "scale": "small",
        "candidates": ["ear decoration", "collar charm", "neck accessory",
                       "small hanging ornament"],
        "reason": ("Rule-based fallback: animal subject must keep its anatomy; "
                   "signature accessory adapted as a small soft-fabric collar charm "
                   "on the neck."),
    },
    "unknown": {
        "adaptation_type": "surface pattern",
        "target_region": "visible exterior surface",
        "material": "original material",
        "scale": "small",
        "candidates": ["surface pattern"],
        "reason": "unknown subject, conservative adaptation",
    },
}

# 各主体的合法 adaptation_type 词表（规格 §8.4 / §19）。
# VLM 返回的词若不在对应词表内（如对杯子返回 "attached"），判定为不可信，
# 整体回退规则表（规则表取值保证是合法名词）。
_ALLOWED_ADAPTATION_TYPES = {
    "human": {"hair accessory", "hair clip", "brooch", "bag charm"},
    "animal": {"ear decoration", "collar charm", "neck accessory", "small hanging ornament"},
    "object": {"surface pattern", "embossed ornament", "painted decoration", "glaze pattern",
               "bag charm", "zipper ornament", "embroidered patch", "small ornament"},
    "unknown": {"collar charm", "surface pattern", "small ornament"},
}


def _palette_text(memory: dict) -> str:
    """从 memory.color_palette 取 main/secondary/accent，拼成 'pink and blue'；
    无有效颜色时返回空字符串（由调用方决定兜底写法）。"""
    cp = (memory or {}).get("color_palette") or {}
    colors = []
    for key in ("main", "secondary", "accent"):
        v = str(cp.get(key, "")).strip().lower()
        if v and v != "unknown" and v not in colors:
            colors.append(v)
    return " and ".join(colors)


def _palette_clause(memory: dict) -> str:
    """配色短语：'pink and blue character color palette'；无有效颜色时 'character color palette'。"""
    palette = _palette_text(memory)
    if not palette:
        return "character color palette"
    return f"{palette} character color palette"


def _style_token(subject_repr: dict, subject_type: str) -> tuple:
    """规格 §17 画风保持 token。返回 (token, default_token)：
    token 命中输入画风时使用 token；未知画风时模板使用 default_token
    （人物默认 anime style——角色本身是动漫角色；其余默认 same visual style as input）。
    """
    style = str((subject_repr or {}).get("style", "")).lower()
    if "oil" in style or "painting" in style:
        return "oil painting" if "oil" in style else "painting", ""
    if "3d" in style or "render" in style:
        return "3D render", ""
    if "pixel" in style:
        return "pixel art, preserve pixelated visual style", ""
    if "realistic" in style or "photo" in style:
        return "photorealistic, preserve photographic appearance", ""
    if "3d" in style:
        return "3D rendered appearance", ""
    if "anime" in style or "illustration" in style or "cartoon" in style:
        return "anime style", ""
    if subject_type == "human":
        return "", "anime style"
    return "", "same visual style as input"


def _object_desc(subject_repr: dict) -> str:
    """物品描述：material + object_category 拼合（§16.3 示例 'ceramic tea cup'）。"""
    sr = subject_repr or {}
    category = known_text(sr.get("object_category"))
    material = known_text(sr.get("material"))
    if category and material:
        return f"{material} {category}"
    return category or material or "object"


class AccessoryAdaptationPlanner:
    """配饰迁移规划器（规格 §19）。

    输入：主体语义表示（subject_repr，来自 S5 的 VLM 主体分析）+ 配饰语义表示（accessory）。
    输出：{adaptation_type, target_region, material, scale, reason}（§19 结构 + source 字段）。

    - 主路径 VLM：需要 self.client 可用且提供了 subject_image（PIL.Image 或路径），
      调用 client.analyze_image(subject_image, ACCESSORY_PROMPT) 规划。
    - 兜底路径：client 为 None / 未提供 subject_image / VLM 失败 -> 规则表（§8.4/§8.5）。
    """

    def __init__(self, client=None, memory=None, subject_image=None):
        self.client = client
        self.memory = memory or {}
        # subject_image: PIL.Image 或图片路径，供 VLM 规划路径参考主体实物（可选）
        self.subject_image = subject_image

    # ---------- 迁移规划 ----------

    def plan(self, subject_repr: dict, accessory: dict) -> dict:
        """生成配饰迁移规划（§19 结构）。

        subject_repr 至少需要 subject_type（human|animal|object|unknown），
        其余字段（material/structure/object_category 等）用于规则细化。
        """
        if not isinstance(subject_repr, dict):
            subject_repr = {"subject_type": "unknown"}
        accessory = accessory if isinstance(accessory, dict) else {}
        if subject_repr.get("subject_type", "unknown") not in {"human", "animal", "object"}:
            return self._rule_plan({"subject_type": "unknown"})
        if (subject_repr.get("subject_type") == "human"
                and "shoulder" in str(accessory.get("normal_usage", ""))
                and region_visible(subject_repr, "torso")):
            return {"adaptation_type": "brooch", "target_region": "shoulder",
                    "material": "enamel", "scale": "small", "source": "source_usage_rule",
                    "reason": "Reference shoulder brooch kept on a visible upper-body region."}

        # ---- 主路径：VLM（需要 client 可用 + 提供主体图片）----
        if (self.client is not None and getattr(self.client, "available", False)
                and self.subject_image is not None):
            try:
                prompt = (ACCESSORY_PROMPT
                          .replace("{{accessory}}", json.dumps(accessory, ensure_ascii=False))
                          .replace("{{subject}}", json.dumps(subject_repr, ensure_ascii=False)))
                result = self.client.analyze_image(self.subject_image, prompt, temperature=0)
                if result:
                    st = str(subject_repr.get("subject_type", "unknown")).lower()
                    if st == "object":
                        checked = validate_object_plan(result, subject_repr)
                        return checked or object_plan(subject_repr)
                    adaptation_type = str(result.get("adaptation_type", "unknown")).strip().lower()
                    target_region = str(result.get("target_region", "unknown")).strip().lower()
                    allowed = _ALLOWED_ADAPTATION_TYPES.get(
                        st, _ALLOWED_ADAPTATION_TYPES["unknown"])
                    # 校验：adaptation_type 必须是该主体的合法名词，否则回退规则表
                    if adaptation_type in allowed and known_text(target_region):
                        plan = {
                            "adaptation_type": adaptation_type,
                            "target_region": target_region,
                            "material": str(result.get("material", "unknown")),
                            "scale": str(result.get("scale", "medium")),
                            "reason": str(result.get("reason", "VLM planning result")),
                            "source": "vlm",
                        }
                        return plan
                    print(f"[semantic_memory] 告警: VLM 规划值不可信（type={adaptation_type!r} "
                          f"region={target_region!r}），回退规则表")
                else:
                    print("[semantic_memory] 告警: VLM 规划返回空，使用规则表兜底")
            except Exception as e:
                print(f"[semantic_memory] 告警: VLM 规划失败（{type(e).__name__}: {e}），"
                      f"使用规则表兜底")
        elif self.client is None or not getattr(self.client, "available", False):
            print("[semantic_memory] 提示: 无可用 VLM，使用规则表兜底规划")

        # ---- 规则表兜底（规格 §8.4 / §8.5）----
        return self._rule_plan(subject_repr)

    def _rule_plan(self, subject_repr: dict) -> dict:
        """人物/动物按类别；物品按材质和可见表面，不枚举物品名称。"""
        st = str(subject_repr.get("subject_type", "unknown")).lower()
        if st == "human":
            base = _RULE_FALLBACKS["human"]
        elif st == "animal":
            base = _RULE_FALLBACKS["animal"]
        elif st == "object":
            return object_plan(subject_repr)
        else:
            base = _RULE_FALLBACKS["unknown"]
        return {**base, "source": "rule"}

    # ---------- 迁移 Prompt 组装（规格 §16 + §17）----------

    def _primary_accessory(self, memory: dict) -> dict:
        """从 memory 取主配饰（accessories[0]，回退 signature_accessories[0]，最后空 dict）。"""
        mem = memory or {}
        for key in ("accessories", "signature_accessories"):
            for it in (mem.get(key) or []):
                if isinstance(it, dict) and it.get("name"):
                    return it
        return {}

    def _accessory_phrase(self, plan: dict, memory: dict, subject_type: str) -> str:
        """配饰改编短语：注入 plan 的 adaptation_type / target_region / material。

        例句（§16.2）：'four_leaf_symbol signature symbol adapted as a small collar charm'
        物品用 transformed into（§16.3 示例风格），其余用 adapted as。
        memory 中没有配饰信息时退化为 'signature symbol ...'（避免词重复）。
        """
        acc = self._primary_accessory(memory)
        name = str(acc.get("name", "") or "").strip()
        color = str(acc.get("color", "") or "")
        name_desc = f"{name} " if name else ""
        color_desc = f" ({color})" if color and color != "unknown" else ""
        scale = str(plan.get("scale", "") or "").strip()
        adaptation_type = str(plan.get("adaptation_type", "ornament") or "ornament")
        region = str(plan.get("target_region", "subject") or "subject")
        material = str(plan.get("material", "matching material") or "matching material")

        if scale:
            # 冠词修饰的是 scale（如 "a medium embossed ornament"），
            # 元音判断必须以 scale 首字母为准（按 adaptation_type 判断会
            # 产生 "an medium" 这类语法错误，实测 bug）
            article = "an" if scale[0].lower() in "aeiou" else "a"
            scale_desc = f"{article} {scale} "
        else:
            scale_desc = ""

        if subject_type == "object":
            return (f"{name_desc}signature symbol{color_desc} transformed into "
                    f"{scale_desc}{adaptation_type} on {region} in {material}")
        return (f"{name_desc}signature symbol{color_desc} adapted as "
                f"{scale_desc}{adaptation_type} on {region} in {material}")

    def build_transfer_prompt(self, subject_repr: dict, plan: dict,
                              memory: dict, trigger: str, category: str = None) -> str:
        """按 subject_type 三模板组装迁移 prompt（规格 §16.1 人物 / §16.2 动物 / §16.3 物品）。

        所有模板均包含：trigger / preserve 结构短语 / 角色配色 / 配饰改编短语
        （注入 plan 的 adaptation_type/target_region/material）/ natural integration /
        画风保持 token（§17）。subject_type 未知时使用保守模板。
        category 为角色类别词（如 1girl），来自 config.get_character_config；
        缺省时回退取当前 CHARACTER_ID 的类别（多角色场景务必由调用方传入）。

        注意：此函数为 VLM 语义记忆路径（memory 来自 output/semantic/*.json）。
        若角色配置了人工校正卡片（config.CHARACTER_CARDS），请改用
        build_card_transfer_prompt（卡片路径优先，VLM 幻觉不再污染 prompt）。
        """
        sr = subject_repr if isinstance(subject_repr, dict) else {}
        st = str(sr.get("subject_type", "unknown")).lower()
        palette = _palette_text(memory)
        palette_clause = _palette_clause(memory)
        style_token, style_default = _style_token(sr, st)
        style_clause = style_token or style_default
        acc_phrase = self._accessory_phrase(plan, memory, st)

        if st == "human":
            # §16.1 人物模板（配色示例 'pink hair', 'blue-pink signature accessory'）
            # 类别词不可硬编码：多角色支持要求按角色 preset 的 category（如 1girl/1boy）注入
            if not category:
                category = config.get_character_config(config.CHARACTER_ID)["category"]
            hair = ((memory or {}).get("appearance") or {}).get("hair", "")
            hair_clause = f"{hair}, " if hair and hair != "unknown" else ""
            sig_clause = f"{palette} signature accessory" if palette else "signature accessory"
            return (f"{trigger}, {category}, preserve original pose, preserve body proportions, "
                    f"character identity, {hair_clause}{sig_clause}, "
                    f"{acc_phrase}, detailed clothing, natural integration, "
                    f"{style_clause}, high quality")
        if st == "animal":
            # §16.2 动物模板
            species = str(sr.get("species", "animal") or "animal")
            return (f"{trigger} character concept, a {species}, preserve {species} anatomy, "
                    f"preserve original pose, {palette_clause}, "
                    f"{acc_phrase}, natural integration, {style_clause}")
        if st == "object":
            # §16.3 物品模板
            return (f"{trigger} character concept, {_object_desc(sr)}, preserve original shape, "
                    f"preserve original composition, {palette_clause}, "
                    f"{acc_phrase}, natural material integration, {style_clause}")
        # unknown 保守模板
        return (f"{trigger} character concept, {st} subject, "
                f"preserve original structure and composition, {palette_clause}, "
                f"{acc_phrase}, natural integration, {style_clause}")

    # ---------- 角色卡片模板（人工校正身份描述，优先于 VLM 语义记忆） ----------

    @staticmethod
    def _count_tokens(text: str, tokenizer, max_tokens: int) -> int:
        """按 CLIP tokenizer 精确计数（无 tokenizer 时按空格粗估）。"""
        if tokenizer is None:
            return len(text.split()) + text.count(", ") // 2
        try:
            return len(tokenizer(text, truncation=False)["input_ids"])
        except Exception:
            return len(text.split())

    @staticmethod
    def _fit_parts(parts, tokenizer, max_tokens: int, drop_priority):
        """按"可丢弃优先级"从尾部裁剪 parts，使合并不超过 max_tokens。

        drop_priority：从最不重要到最重要的可丢弃短语列表（不含身份核心）。
        若裁剪后仍超限，打印警告（身份标签是硬底，不宜继续裁剪）。
        """
        parts = [p for p in parts if p]
        while True:
            joined = ", ".join(parts)
            if tokenizer is None:
                n = len(joined.split())
            else:
                try:
                    n = len(tokenizer(joined, truncation=False)["input_ids"])
                except Exception:
                    n = len(joined.split())
            if n <= max_tokens:
                return parts
            dropped = False
            for prio in drop_priority:          # 从最低优先级开始尝试
                if prio in parts:
                    parts.remove(prio)
                    dropped = True
                    break
            if not dropped:
                print(f"[semantic_memory] 警告: prompt 裁剪后仍超长（{n} > {max_tokens}），"
                      "请精简 config.CHARACTER_CARDS 的 identity_tags/quality_tags")
                break
        return parts

    def build_card_transfer_prompt(self, subject_repr: dict, plan: dict,
                                   card: dict, trigger: str, category: str = None,
                                   tokenizer=None, max_tokens: int = 76,
                                   tokenizer_2=None) -> str:
        """按角色卡片（config.CHARACTER_CARDS）组装迁移 prompt。

        与 build_transfer_prompt 的区别：
        - 身份描述来自人工校对的卡片（identity_tags / quality_tags / palette /
          accessory），不再依赖 VLM 角色解析（实测 Qwen2.5-VL 会把粉发角色
          幻觉成 "light blue hair / Flower Fairy"，直接毒化 prompt）；
        - 删除 "character identity / natural integration" 等无信息空词，改为
          底模熟悉的 Danbooru 风格标签；
        - 风格策略二选一（card.style_policy）：
            "character" -> 输出统一为角色画风（card.style，默认 anime style），
                           对应示例 37_1/37_3（油画/涂鸦输入 -> 动漫角色）；
            "preserve"  -> 保留输入画风（走 _style_token 画风映射），
                           对应示例 37_2（照片猫保持照片感，只换配色/配饰）。
        - 人际身份标签（pink hair 等）只注入 human 主体；animal/object 只注入
          palette + 配饰短语，防止"粉发猫娘/穿裙子杯子"这类拟人污染（规格 §18.2）。
        - 检查两个 CLIP tokenizer 的完整长度（含 BOS/EOS）。必需条件超限
          明确报错；可选条件逐项尝试填入余量，不再删除画风/结构来保身份长串。

        card 空 dict 时回退 build_transfer_prompt（兼容无卡片角色）。
        """
        if not card:
            return self.build_transfer_prompt(subject_repr, plan, {}, trigger, category)

        return self._build_grounded_card_prompt(subject_repr, plan, card, trigger,
                                                category, tokenizer, tokenizer_2, max_tokens)

    def _build_grounded_card_prompt(self, subject_repr, plan, card, trigger,
                                    category, tokenizer, tokenizer_2, max_tokens):
        sr = subject_repr or {}
        st = sr.get("subject_type", "unknown")
        constraints, _ = composition_constraints(sr)
        if style_policy_for_subject(card, sr) == "character":
            style = card.get("style", "anime style")
        else:
            style, _ = _style_token(sr, st)
            # Keep the style label compact; structural conditions have their own slots.
            style = style.split(",")[0]
        acc = card.get("accessory") or {}
        description = acc.get("description") or ", ".join(
            str(acc.get(k) or "") for k in ("color", "shape", "name"))
        form = str(plan.get("adaptation_type") or "small ornament")
        region = str(plan.get("target_region") or "main surface")
        required = [trigger]
        optional = []
        palette = list(dict.fromkeys(known_text(c) for c in card.get("palette", [])
                                     if known_text(c)))[:3]
        color_design = " ".join(palette) + " color scheme" if palette else ""
        if st == "human":
            required += [category or "person"] + constraints
            if region_visible(sr, "head") or not sr.get("visible_regions"):
                required += [t.strip() for t in card.get("core_identity_tags", "").split(",")]
            # Human identity includes the visible outfit, not just hair plus a badge.
            for region_name, tags in (card.get("human_required_regions") or {}).items():
                if region_visible(sr, region_name):
                    required.append(tags)
            human_description = acc.get("human_description") or description
            required += [f"{human_description} on {region}", style]
            # Detailed accessory geometry remains mandatory on non-human subjects.
            for region_name, tags in (card.get("regional_identity_tags") or {}).items():
                if region_visible(sr, region_name):
                    optional.append(tags)
            reserved = {t.strip() for phrase in required for t in phrase.split(",")}
            optional += [t.strip() for t in card.get("identity_tags", "").split(",")
                         if t.strip() not in reserved]
        elif st == "animal":
            required += [str(sr.get("species") or "animal"), "natural animal anatomy",
                         color_design, f"{form} on {region}", description, style]
            optional += [known_text(sr.get("material")), str(plan.get("material") or "")]
        elif st == "object":
            required += [_object_desc(sr), "original shape and parts", color_design,
                         f"{form} on {region}", description, style]
            optional += ["color blocking", "preserve texture", str(plan.get("material") or "")]
        else:
            required += ["original subject", "original structure", description, style]
        quality = [t.strip() for t in card.get("quality_tags", "").split(",")]
        optional = quality + optional if st == "human" else optional + quality
        prompt, dropped = fit_prompt(required, optional, (tokenizer, tokenizer_2), max_tokens)
        self.last_prompt_audit = {"required": required, "dropped_optional": dropped,
                                  "max_tokens": max_tokens}
        return prompt


if __name__ == "__main__":
    """自检块（PyCharm 直接运行）：不加载 VLM，验证 offline 记忆生成与规则表规划。"""
    print("=" * 60)
    print("character/semantic_memory.py 自检")
    print("=" * 60)

    # 1. offline 记忆生成（无 VLM）
    memory = generate_character_memory(config.CHARACTER_ID, client=None)
    print(f"[1] offline 记忆已生成: folder={memory['folder']} source={memory['source']}")

    # 2. 二次读取应直接读文件
    memory2 = load_character_memory(config.CHARACTER_ID, client=None)
    print(f"[2] 二次读取: identity={memory2['identity']!r}")

    # 3. 规则表兜底验证（假 subject_repr）
    fake_subjects = {
        "human": {"subject_type": "human", "pose": "standing", "style": "realistic photo"},
        "cat": {"subject_type": "animal", "species": "cat", "pose": "sitting",
                "material": "fur", "attachment_regions": ["ear", "neck"]},
        "cup": {"subject_type": "object", "object_category": "cup", "material": "ceramic",
                "structure": ["cup body", "handle"], "surface_regions": ["cup body"]},
        "bag": {"subject_type": "object", "object_category": "backpack", "material": "canvas",
                "structure": ["bag body", "zipper"], "surface_regions": ["bag surface"]},
    }
    fake_accessory = {"name": "four_leaf_symbol", "shape": "four leaf",
                      "color": ["blue", "pink"], "role": "signature identity symbol"}
    planner = AccessoryAdaptationPlanner(client=None, memory=memory)
    print("[3] 规则表规划结果：")
    for name, sr in fake_subjects.items():
        plan = planner.plan(sr, fake_accessory)
        print(f"    {name:6s} -> {json.dumps(plan, ensure_ascii=False)}")

    # 4. 四种模板样例
    print("[4] build_transfer_prompt 四种模板样例：")
    for name, sr in fake_subjects.items():
        plan = planner.plan(sr, fake_accessory)
        prompt = planner.build_transfer_prompt(sr, plan, memory, config.get_trigger(config.CHARACTER_ID))
        print(f"    ---- {name} ----")
        print(f"    {prompt}")

    # 5. unknown 保守路径
    plan_u = planner.plan({"subject_type": "unknown"}, fake_accessory)
    print(f"[5] unknown 规划: {json.dumps(plan_u, ensure_ascii=False)}")

    print("=" * 60)
